version: '3'
services:
  kafka_0_8:
    image: sspinc/kafka
    environment:
      - ADVERTISED_HOST=${ADVERTISED_HOST}
      - ADVERTISED_PORT=${KAFKA_0_8_PORT}
    ports:
      - ${KAFKA_0_8_PORT}:${KAFKA_0_8_PORT}
      - ${ZOOKEEPER_EXTERNAL_PORT}:2181
  kafka_0_10:
    image: ches/kafka:0.10.2.1
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=${ADVERTISED_HOST}
      - KAFKA_ADVERTISED_PORT=${KAFKA_0_10_PORT}
      - KAFKA_PORT=${KAFKA_0_10_PORT}
      - ZOOKEEPER_IP=zookeeper
    ports:
      - ${KAFKA_0_10_PORT}:${KAFKA_0_10_PORT}
    links:
      - zookeeper
  zookeeper:
    image: zookeeper:3.4
    expose:
      - "2181"
